# https://github.com/cosmtrek/air/blob/master/air_example.toml TOML 格式的配置文件

# 工作目录
# 使用 . 或 绝对路径, 请注意 `tmp_dir` 目录必须在 `root` 目录下
root = "."
tmp_dir = "tmp"

[build]
# 只需要写你平常编译使用的shell命令。你也可以使用 `make`
cmd = "go build -o ./tmp/main ."
# 由`cmd`命令得到的二进制文件名
bin = "tmp/main"
# 自定义参数，可以添加额外的编译标识，例如添加 GIN_MODE=release
full_bin = ""
# 监听以下指定扩展名的文件.
include_ext = ["go", "tpl", "tmpl", "html", "gohtml", "env"]
# 忽略这些文件扩展名或目录
exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules", "public/uploads"]
# 监控以下目录的文件
include_dir = []
# 忽略以下文件
exclude_file = []
# 使用正则表达式进行忽略文件设置
exclude_regex = ["_test.go"]
# 忽略未变更的文件
exclude_unchanged = true
# 监控系统链接的目录
follow_symlink = true
# air的日志文件名，该日志文件放置在你的`tmp_dir`中
log = "air.log"
# 如果文件更改过于频繁，则没有必要在每次更改时都触发构建。可以设置触发构建的延迟时间
delay = 1000 # ms
# error 发生时结束运行
stop_on_error = true
# 在 kill 之前发送系统中断信号，windows 不支持此功能
send_interrupt = false
# kill 命令延迟
kill_delay = 500 # ms

[log]
# 显示日志时间
time = false

[color]
# 自定义每个部分显示的颜色。如果找不到颜色，使用原始的应用程序日志。
app = ""
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# 退出时删除tmp目录
clean_on_exit = true